### ISSUE TITLE
Criação da página Sobre

### ISSUE THREAD

**Issue by accolombinifake** [accolombini/github-master#3]
Vocês poderiam criar uma página sobre? Agradeço.

**Comment by accolombini** [comment]
A página está em construção

**Comment by accolombinifake** [comment]
Obrigado, estou aguardando.
________________________________
De: Angelo <notifications@github.com>
Enviado: 7 de janeiro de 2020 16:14
Para: accolombini/github-master <github-master@noreply.github.com>
Cc: accolombinifake <accolombinifake@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [accolombini/github-master] Criação da página Sobre (#3)


A página está em construção
